package proyecto_agentes;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;

/**
 * modelo Java Implementation.
 * 
 * Generated by AMF for model: modelo.metaabm in project: proyecto_agentes 
 */
public class Modelo3D extends Modelo {

	public void createGraphicViews() {
		addView(new GEF3DView());
	}
}
