package proyecto_agentes;

import org.ascape.util.vis.ColorFeature;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;
import org.eclipse.draw2d.Shape;
import org.eclipse.draw2d.ColorConstants;

import org.eclipse.jface.viewers.IColorProvider;

/**
 * Sensor Ambiental Style 2D Java Implementation.
 * 
 * Generated by AMF for model: modelo.metaabm in project: proyecto_agentes 
 */
public class SensorAmbientalStyle2DColorProvider implements IColorProvider {

	private static IColorProvider singleton;

	/**
	 * Provides a color for Sensor Ambiental based on wether we want to fill or not.
	 * 
	 * @param object the agent
	 * @return	the foreground color for the element, or <code>null</code> 
	 *   to use the default foreground color
	 */
	public Color getColor(Object object, boolean fill) {
		Color color = null;
		Color fillColor = null;
		Color outlineColor = null;

		SensorAmbiental actions = (SensorAmbiental) object;
		SensorAmbiental defaultmodeloAgentStyle = actions;
		fillColor = ColorConstants.blue;
		if (fill) {
			return fillColor;
		} else {
			return outlineColor;
		}
	}

	/**
	 * Provides a foreground color for the given Sensor Ambiental.
	 * 
	 * @param object the agent
	 * @return	the foreground color for the element, or <code>null</code> 
	 *   to use the default foreground color
	 */
	public Color getForeground(Object object) {
		Color color = getColor(object, false);
		if (color != null) {
			return color;
		}
		//try to see if we have a fill color, if we do, we'll paint the whole agent that color.
		color = getColor(object, true);
		if (color != null) {
			return color;
		}
		return ColorFeature.BLACK;
	}

	/**
	 * Provides a background color for the given Sensor Ambiental.
	 * 
	 * @param object the agent
	 * @return	the background color for the element, or <code>null</code> 
	 *   to use the default background color
	 */
	public Color getBackground(Object object) {
		Color color = getColor(object, true);
		if (color != null) {
			return color;
		}
		//if no fill color, just return white
		return ColorFeature.WHITE;
	}

	public static IColorProvider getDefault() {
		if (singleton == null) {
			singleton = new SensorAmbientalStyle2DColorProvider();
		}
		return singleton;
	}
}
