package proyecto_agentes;

import org.ascape.util.vis.ColorFeature;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;
import org.eclipse.draw2d.IFigure;
import org.eclipse.draw2d.Shape;
import org.eclipse.draw2d.ColorConstants;

import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.amp.agf.gef.DefaultFigureProvider;
import org.eclipse.amp.agf.gef.Shapes;

/**
 * Sensor Ambiental Style 2D Java Implementation.
 * 
 * Generated by AMF for model: modelo.metaabm in project: proyecto_agentes 
 */
public class SensorAmbientalStyle2DFigureProvider extends DefaultFigureProvider {

	private static IFigureProvider singleton;

	public IFigure getFigure(Object object) {
		IFigure figure = null;
		Color color = null;
		SensorAmbiental actions = (SensorAmbiental) object;
		SensorAmbiental defaultmodeloAgentStyle = actions;
		if (figure == null) {
			figure = Shapes.createOval();
		}
		color = ColorConstants.blue;

		figure.setBackgroundColor(color);
		((Shape) figure).setFill(true);
		return figure;
	}

	public static IFigureProvider getDefault() {
		if (singleton == null) {
			singleton = new SensorAmbientalStyle2DFigureProvider();
		}
		return singleton;
	}
}
